### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by MattRutherford** [heroku/heroku-pg-extras#155] opened 2018-01-09 22:56 UTC
All commands fail with error, eg: 

```
$ heroku pg:cache-hit
 ▸    Unknown database: undefined. Valid options are: HEROKU_POSTGRESQL_GREEN_URL

$ heroku pg:cache-hit HEROKU_POSTGRESQL_GREEN_URL
 ▸    Cannot read property 'startsWith' of undefined
```

Error log:

```
2018/01/09 17:46:56 TypeError: Cannot read property 'startsWith' of undefined
    at attachment.config_vars.filter (/Users/matt/.local/share/heroku/plugins/node_modules/heroku-pg/lib/util.js:17:81)
    at Array.filter (<anonymous>)
    at Object.exports.getConnectionDetails (/Users/matt/.local/share/heroku/plugins/node_modules/heroku-pg/lib/util.js:17:55)
    at Object.database (/Users/matt/.local/share/heroku/plugins/node_modules/heroku-pg/lib/fetcher.js:94:19)
    at database.next (<anonymous>)
    at onFulfilled (/Users/matt/.local/share/heroku/plugins/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by uhoh-itsmaciek** [comment] 2018-01-10 01:52
I can't reproduce this. Can you tell us the output of `heroku version` and the `heroku-pg` and `heroku-pg-extras` lines from the output of `heroku plugins`?

**Comment by MattRutherford** [comment] 2018-01-10 08:31
Thanks. It's:

```
$ heroku version
heroku-cli/6.15.13-3dce47c (darwin-x64) node-v9.3.0
```
```
$ heroku plugins
heroku-pg 2.4.1
heroku-pg-extras 1.1.1
semver 5.3.0 (~5.3.0)
```

**Comment by uhoh-itsmaciek** [comment] 2018-01-11 00:42
Closing as this was handled via support ticket (leading to [this workaround](https://github.com/heroku/heroku-pg/pull/178)--thanks!). Please let us know if you still have issues.

**Closed by uhoh-itsmaciek** 2018-01-11 00:42 UTC

**Comment by MattRutherford** [comment] 2018-01-11 09:24
That fixed the issue. thanks. I'm wondering how common this is and if creating a wiki for it might help?

**Comment by uhoh-itsmaciek** [comment] 2018-01-16 17:12
I think a wiki would have discoverability issues. The workaround we shipped that I linked above should make it obvious what's going on, no?
